spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "[spring.json.type.mapping]": foo:io.duhan.springkafka.dto.Foo1,bar:io.duhan.springkafka.dto.Bar1
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
